/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef StudentService_H
#define StudentService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "student_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class StudentServiceIf {
 public:
  virtual ~StudentServiceIf() {}
  virtual void put(const Student& student) = 0;
  virtual void get(Student& _return, const int32_t sno) = 0;
};

class StudentServiceIfFactory {
 public:
  typedef StudentServiceIf Handler;

  virtual ~StudentServiceIfFactory() {}

  virtual StudentServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(StudentServiceIf* /* handler */) = 0;
};

class StudentServiceIfSingletonFactory : virtual public StudentServiceIfFactory {
 public:
  StudentServiceIfSingletonFactory(const boost::shared_ptr<StudentServiceIf>& iface) : iface_(iface) {}
  virtual ~StudentServiceIfSingletonFactory() {}

  virtual StudentServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(StudentServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<StudentServiceIf> iface_;
};

class StudentServiceNull : virtual public StudentServiceIf {
 public:
  virtual ~StudentServiceNull() {}
  void put(const Student& /* student */) {
    return;
  }
  void get(Student& /* _return */, const int32_t /* sno */) {
    return;
  }
};

typedef struct _StudentService_put_args__isset {
  _StudentService_put_args__isset() : student(false) {}
  bool student :1;
} _StudentService_put_args__isset;

class StudentService_put_args {
 public:

  StudentService_put_args(const StudentService_put_args&);
  StudentService_put_args& operator=(const StudentService_put_args&);
  StudentService_put_args() {
  }

  virtual ~StudentService_put_args() throw();
  Student student;

  _StudentService_put_args__isset __isset;

  void __set_student(const Student& val);

  bool operator == (const StudentService_put_args & rhs) const
  {
    if (!(student == rhs.student))
      return false;
    return true;
  }
  bool operator != (const StudentService_put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StudentService_put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StudentService_put_pargs {
 public:


  virtual ~StudentService_put_pargs() throw();
  const Student* student;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StudentService_put_result {
 public:

  StudentService_put_result(const StudentService_put_result&);
  StudentService_put_result& operator=(const StudentService_put_result&);
  StudentService_put_result() {
  }

  virtual ~StudentService_put_result() throw();

  bool operator == (const StudentService_put_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const StudentService_put_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StudentService_put_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StudentService_put_presult {
 public:


  virtual ~StudentService_put_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _StudentService_get_args__isset {
  _StudentService_get_args__isset() : sno(false) {}
  bool sno :1;
} _StudentService_get_args__isset;

class StudentService_get_args {
 public:

  StudentService_get_args(const StudentService_get_args&);
  StudentService_get_args& operator=(const StudentService_get_args&);
  StudentService_get_args() : sno(0) {
  }

  virtual ~StudentService_get_args() throw();
  int32_t sno;

  _StudentService_get_args__isset __isset;

  void __set_sno(const int32_t val);

  bool operator == (const StudentService_get_args & rhs) const
  {
    if (!(sno == rhs.sno))
      return false;
    return true;
  }
  bool operator != (const StudentService_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StudentService_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class StudentService_get_pargs {
 public:


  virtual ~StudentService_get_pargs() throw();
  const int32_t* sno;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StudentService_get_result__isset {
  _StudentService_get_result__isset() : success(false) {}
  bool success :1;
} _StudentService_get_result__isset;

class StudentService_get_result {
 public:

  StudentService_get_result(const StudentService_get_result&);
  StudentService_get_result& operator=(const StudentService_get_result&);
  StudentService_get_result() {
  }

  virtual ~StudentService_get_result() throw();
  Student success;

  _StudentService_get_result__isset __isset;

  void __set_success(const Student& val);

  bool operator == (const StudentService_get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const StudentService_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StudentService_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _StudentService_get_presult__isset {
  _StudentService_get_presult__isset() : success(false) {}
  bool success :1;
} _StudentService_get_presult__isset;

class StudentService_get_presult {
 public:


  virtual ~StudentService_get_presult() throw();
  Student* success;

  _StudentService_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class StudentServiceClient : virtual public StudentServiceIf {
 public:
  StudentServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  StudentServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(const Student& student);
  void send_put(const Student& student);
  void recv_put();
  void get(Student& _return, const int32_t sno);
  void send_get(const int32_t sno);
  void recv_get(Student& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class StudentServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<StudentServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (StudentServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  StudentServiceProcessor(boost::shared_ptr<StudentServiceIf> iface) :
    iface_(iface) {
    processMap_["put"] = &StudentServiceProcessor::process_put;
    processMap_["get"] = &StudentServiceProcessor::process_get;
  }

  virtual ~StudentServiceProcessor() {}
};

class StudentServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  StudentServiceProcessorFactory(const ::boost::shared_ptr< StudentServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< StudentServiceIfFactory > handlerFactory_;
};

class StudentServiceMultiface : virtual public StudentServiceIf {
 public:
  StudentServiceMultiface(std::vector<boost::shared_ptr<StudentServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~StudentServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<StudentServiceIf> > ifaces_;
  StudentServiceMultiface() {}
  void add(boost::shared_ptr<StudentServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void put(const Student& student) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->put(student);
    }
    ifaces_[i]->put(student);
  }

  void get(Student& _return, const int32_t sno) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, sno);
    }
    ifaces_[i]->get(_return, sno);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class StudentServiceConcurrentClient : virtual public StudentServiceIf {
 public:
  StudentServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  StudentServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(const Student& student);
  int32_t send_put(const Student& student);
  void recv_put(const int32_t seqid);
  void get(Student& _return, const int32_t sno);
  int32_t send_get(const int32_t sno);
  void recv_get(Student& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
