/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef testMapService_H
#define testMapService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "test_map_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class testMapServiceIf {
 public:
  virtual ~testMapServiceIf() {}
  virtual void pushData(const int64_t reqId, const std::map<int64_t, std::string> & pushData) = 0;
};

class testMapServiceIfFactory {
 public:
  typedef testMapServiceIf Handler;

  virtual ~testMapServiceIfFactory() {}

  virtual testMapServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(testMapServiceIf* /* handler */) = 0;
};

class testMapServiceIfSingletonFactory : virtual public testMapServiceIfFactory {
 public:
  testMapServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<testMapServiceIf>& iface) : iface_(iface) {}
  virtual ~testMapServiceIfSingletonFactory() {}

  virtual testMapServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(testMapServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<testMapServiceIf> iface_;
};

class testMapServiceNull : virtual public testMapServiceIf {
 public:
  virtual ~testMapServiceNull() {}
  void pushData(const int64_t /* reqId */, const std::map<int64_t, std::string> & /* pushData */) {
    return;
  }
};

typedef struct _testMapService_pushData_args__isset {
  _testMapService_pushData_args__isset() : reqId(false), pushData(false) {}
  bool reqId :1;
  bool pushData :1;
} _testMapService_pushData_args__isset;

class testMapService_pushData_args {
 public:

  testMapService_pushData_args(const testMapService_pushData_args&);
  testMapService_pushData_args& operator=(const testMapService_pushData_args&);
  testMapService_pushData_args() : reqId(0) {
  }

  virtual ~testMapService_pushData_args() throw();
  int64_t reqId;
  std::map<int64_t, std::string>  pushData;

  _testMapService_pushData_args__isset __isset;

  void __set_reqId(const int64_t val);

  void __set_pushData(const std::map<int64_t, std::string> & val);

  bool operator == (const testMapService_pushData_args & rhs) const
  {
    if (!(reqId == rhs.reqId))
      return false;
    if (!(pushData == rhs.pushData))
      return false;
    return true;
  }
  bool operator != (const testMapService_pushData_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const testMapService_pushData_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class testMapService_pushData_pargs {
 public:


  virtual ~testMapService_pushData_pargs() throw();
  const int64_t* reqId;
  const std::map<int64_t, std::string> * pushData;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class testMapService_pushData_result {
 public:

  testMapService_pushData_result(const testMapService_pushData_result&);
  testMapService_pushData_result& operator=(const testMapService_pushData_result&);
  testMapService_pushData_result() {
  }

  virtual ~testMapService_pushData_result() throw();

  bool operator == (const testMapService_pushData_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const testMapService_pushData_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const testMapService_pushData_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class testMapService_pushData_presult {
 public:


  virtual ~testMapService_pushData_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class testMapServiceClient : virtual public testMapServiceIf {
 public:
  testMapServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  testMapServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void pushData(const int64_t reqId, const std::map<int64_t, std::string> & pushData);
  void send_pushData(const int64_t reqId, const std::map<int64_t, std::string> & pushData);
  void recv_pushData();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class testMapServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<testMapServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (testMapServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_pushData(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  testMapServiceProcessor(::apache::thrift::stdcxx::shared_ptr<testMapServiceIf> iface) :
    iface_(iface) {
    processMap_["pushData"] = &testMapServiceProcessor::process_pushData;
  }

  virtual ~testMapServiceProcessor() {}
};

class testMapServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  testMapServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< testMapServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< testMapServiceIfFactory > handlerFactory_;
};

class testMapServiceMultiface : virtual public testMapServiceIf {
 public:
  testMapServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<testMapServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~testMapServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<testMapServiceIf> > ifaces_;
  testMapServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<testMapServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void pushData(const int64_t reqId, const std::map<int64_t, std::string> & pushData) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->pushData(reqId, pushData);
    }
    ifaces_[i]->pushData(reqId, pushData);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class testMapServiceConcurrentClient : virtual public testMapServiceIf {
 public:
  testMapServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  testMapServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void pushData(const int64_t reqId, const std::map<int64_t, std::string> & pushData);
  int32_t send_pushData(const int64_t reqId, const std::map<int64_t, std::string> & pushData);
  void recv_pushData(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
