/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_map_constants.h"



const test_mapConstants g_test_map_constants;

test_mapConstants::test_mapConstants() {
}



