/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_map_CONSTANTS_H
#define test_map_CONSTANTS_H

#include "test_map_types.h"



class test_mapConstants {
 public:
  test_mapConstants();

};

extern const test_mapConstants g_test_map_constants;



#endif
